apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - secret/secret.yaml
  - auth-db/persistent-volume-claim.yaml
  - auth-db/deployment.yaml
  - auth-db/service.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - back/deployment.yaml
  - back/service.yaml
  - front/deployment.yaml
  - front/service.yaml
  - ingress/ingress.yaml
