apiVersion: v1
kind: Secret
metadata:
  name: poke-secrets
  namespace: poke-app
type: Opaque
stringData:
  postgres-password: poke
  jwt-key: super-secret-development-key-change-me
  auth-db-url: jdbc:postgresql://auth-db:5432/poke_auth?user=poke&password=poke
