apiVersion: v1
kind: Secret
metadata:
  name: poke-secrets
  namespace: poke-app
type: Opaque
stringData:
  postgres-password: poke
  jwt-key: super-secret-development-key-change-me
  auth-db-connection-string: Host=auth-db;Port=5432;Database=poke_auth;Username=poke;Password=poke
